[package]
name = "mikrosdk"
version = "0.1.1"
edition = "2024"
author =  ["Leon Besnie leon.besnie@reseau.eseo.fr"]


[profile.release]
opt-level = 'z' 
lto = true
panic = "abort"


[profile.dev]
opt-level = 0 
lto = false
panic = "abort"


[dependencies]

cortex-m = "0.7.7"      # Access to the generic ARM peripherals
cortex-m-rt = "0.7.5"  # Startup code for the ARM Core
panic-halt = "1.0.0"    # Panic handler

mcu = { path = "core/mcu"}
hal_ll_gpio_port = { path = "hal_ll/gpio/hal_ll_gpio_port" }


[features]
