[package]
name = "hal_ll"
version = "0.1.0"
edition = "2024"
author =  ["Leon Besnie leon.besnie@reseau.eseo.fr"]


[profile.release]
opt-level = 'z' 
lto = true


[profile.dev]
opt-level = 0 
lto = false  


[dependencies]

hal_ll_adc = {path = "{adc_path}", optional = true}
hal_ll_i2c_master = {path = "{i2c_path}", optional = true}
hal_ll_spi_master = {path = "{spi_path}", optional = true}
hal_ll_tim = {path = "{tim_path}", optional = true}
hal_ll_uart = {path = "{uart_path}", optional = true}
hal_ll_one_wire = {path = "{one_wire_path}", optional = true}


system = {path = "../core/system"}

[features]
adc = ["hal_ll_adc/adc", "dep:hal_ll_adc", {adc}]

adc1 = ["hal_ll_adc/adc1"]
adc2 = ["hal_ll_adc/adc2"]
adc3 = ["hal_ll_adc/adc3"]

i2c = ["hal_ll_i2c_master/i2c", "dep:hal_ll_i2c_master",{i2c}]

i2c1 = ["hal_ll_i2c_master/i2c1"]
i2c2 = ["hal_ll_i2c_master/i2c2"]
i2c3 = ["hal_ll_i2c_master/i2c3"]

spi = ["hal_ll_spi_master/spi", "dep:hal_ll_spi_master",{spi}]

spi1 = ["hal_ll_spi_master/spi1"]
spi2 = ["hal_ll_spi_master/spi2"]
spi3 = ["hal_ll_spi_master/spi3"]
spi4 = ["hal_ll_spi_master/spi4"]
spi5 = ["hal_ll_spi_master/spi5"]
spi6 = ["hal_ll_spi_master/spi6"]

tim = ["hal_ll_tim/tim", "dep:hal_ll_tim",{tim}]

tim1 = ["hal_ll_tim/tim1"]
tim2 = ["hal_ll_tim/tim2"]
tim3 = ["hal_ll_tim/tim3"]
tim4 = ["hal_ll_tim/tim4"]
tim5 = ["hal_ll_tim/tim5"]
tim8 = ["hal_ll_tim/tim8"]
tim9 = ["hal_ll_tim/tim9"]
tim10 = ["hal_ll_tim/tim10"]
tim11 = ["hal_ll_tim/tim11"]
tim12 = ["hal_ll_tim/tim12"]
tim13 = ["hal_ll_tim/tim13"]
tim14 = ["hal_ll_tim/tim14"]

uart = ["hal_ll_uart/uart", "dep:hal_ll_uart",{uart}]

uart1 = ["hal_ll_uart/uart1"]
uart2 = ["hal_ll_uart/uart2"]
uart3 = ["hal_ll_uart/uart3"]
uart4 = ["hal_ll_uart/uart4"]
uart5 = ["hal_ll_uart/uart5"]
uart6 = ["hal_ll_uart/uart6"]
uart7 = ["hal_ll_uart/uart7"]
uart8 = ["hal_ll_uart/uart8"]

one_wire = ["hal_ll_one_wire/one_wire", "dep:hal_ll_one_wire"]